=== antarctica/metadata-library/src/bas_metadata_library/schemas/dist/magic_discovery_v2.json
{
    "$id": "https://metadata-resources.data.bas.ac.uk/bas-metadata-generator-configuration-schemas/v2/magic-discovery-v2.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "BAS MAGIC Discovery Metadata Profile v2 configuration schema",
    "description": "Metadata record configuration schema for the BAS MAGIC Discovery Metadata profile (version 2).\n\nThis schema does not fully validate reqs. 06 & 07 (Released Date & Publication Date) due to limitations in property names and overlaying schemas.",
    "$defs": {
        "_container_types": {
            "enum": [
                "collection",
                "fieldSession",
                "initiative"
            ]
        },
        "_resource_types": {
            "enum": [
                "dataset",
                "feature",
                "product",
                "mapProduct",
                "paperMapProduct",
                "webMapProduct",
                "series"
            ]
        },
        "catalogue_identifier": {
            "title": "Req. 04 - Data Catalogue Identifier",
            "type": "object",
            "required": [
                "identifier",
                "href",
                "namespace"
            ],
            "properties": {
                "identifier": {
                    "type": "string"
                },
                "href": {
                    "type": "string",
                    "pattern": "^https://data\\.bas\\.ac\\.uk/items/.+"
                },
                "namespace": {
                    "type": "string",
                    "const": "data.bas.ac.uk"
                }
            }
        },
        "constraints": {
            "type": "array",
            "allOf": [
                {
                    "contains": {
                        "title": "Req. 09 - Access Constraint",
                        "type": "object",
                        "required": [
                            "type"
                        ],
                        "properties": {
                            "type": {
                                "type": "string",
                                "const": "access"
                            }
                        }
                    }
                },
                {
                    "contains": {
                        "title": "Req. 10 - Usage Constraint (Licence)",
                        "type": "object",
                        "required": [
                            "type"
                        ],
                        "properties": {
                            "type": {
                                "type": "string",
                                "const": "usage"
                            }
                        }
                    }
                }
            ]
        },
        "contacts": {
            "type": "array",
            "allOf": [
                {
                    "contains": {
                        "$ref": "#/$defs/point_of_contact"
                    }
                },
                {
                    "contains": {
                        "$ref": "#/$defs/copyright_holder"
                    }
                }
            ]
        },
        "copyright_holder": {
            "title": "Req. 16 - Copyright Holder",
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "array",
                    "contains": {
                        "type": "string",
                        "const": "rightsHolder"
                    }
                }
            }
        },
        "domain_conformance": {
            "title": "Req. 02 - Domain Consistency/Conformance",
            "type": "object",
            "required": [
                "specification",
                "explanation",
                "result"
            ],
            "properties": {
                "specification": {
                    "type": "object",
                    "required": [
                        "title",
                        "dates",
                        "edition",
                        "contact"
                    ],
                    "properties": {
                        "title": {
                            "type": "object",
                            "required": [
                                "value",
                                "href"
                            ],
                            "properties": {
                                "value": {
                                    "type": "string",
                                    "const": "British Antarctic Survey (BAS) Mapping and Geographic Information Centre (MAGIC) Discovery Metadata Profile"
                                },
                                "href": {
                                    "type": "string",
                                    "const": "https://metadata-standards.data.bas.ac.uk/profiles/magic-discovery/v2/"
                                }
                            }
                        },
                        "dates": {
                            "type": "object",
                            "required": [
                                "publication"
                            ],
                            "properties": {
                                "publication": {
                                    "type": "string",
                                    "const": "2025-11-24"
                                }
                            }
                        },
                        "edition": {
                            "type": "string",
                            "const": "2"
                        },
                        "contact": {
                            "allOf": [
                                {
                                    "$ref": "#/$defs/magic"
                                },
                                {
                                    "type": "object",
                                    "required": [
                                        "role"
                                    ],
                                    "properties": {
                                        "role": {
                                            "type": "array",
                                            "contains": {
                                                "type": "string",
                                                "const": "publisher"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                },
                "explanation": {
                    "type": "string",
                    "const": "Resource within scope of the British Antarctic Survey (BAS) Mapping and Geographic Information Centre (MAGIC) Discovery Metadata Profile."
                },
                "result": {
                    "type": "boolean",
                    "const": true
                }
            }
        },
        "domain_consistency": {
            "type": "array",
            "contains": {
                "$ref": "#/$defs/domain_conformance"
            }
        },
        "extents": {
            "title": "Req. 14 - Geographic Extent",
            "type": "array",
            "contains": {
                "type": "object",
                "required": [
                    "identifier"
                ],
                "properties": {
                    "identifier": {
                        "type": "string",
                        "const": "bounding"
                    }
                }
            }
        },
        "hierarchy_level": {
            "title": "Req. 03 - Hierarchy Level",
            "oneOf": [
                {
                    "$ref": "#/$defs/_container_types"
                },
                {
                    "$ref": "#/$defs/_resource_types"
                }
            ]
        },
        "identification": {
            "title": "Req. 05 - Edition",
            "type": "object",
            "required": [
                "dates",
                "edition",
                "identifiers",
                "contacts",
                "maintenance",
                "constraints",
                "extents",
                "domain_consistency"
            ],
            "properties": {
                "identifiers": {
                    "$ref": "#/$defs/identifiers"
                },
                "contacts": {
                    "$ref": "#/$defs/contacts"
                },
                "maintenance": {
                    "$ref": "#/$defs/maintenance"
                },
                "constraints": {
                    "$ref": "#/$defs/constraints"
                },
                "extents": {
                    "$ref": "#/$defs/extents"
                },
                "lineage": {
                    "$ref": "#/$defs/lineage"
                },
                "domain_consistency": {
                    "$ref": "#/$defs/domain_consistency"
                }
            }
        },
        "identifiers": {
            "type": "array",
            "contains": {
                "$ref": "#/$defs/catalogue_identifier"
            }
        },
        "lineage": {
            "title": "Req. 13 - Lineage statement",
            "type": "object",
            "required": [
                "statement"
            ]
        },
        "magic": {
            "type": "object",
            "required": [
                "organisation",
                "phone",
                "address",
                "email",
                "online_resource"
            ],
            "properties": {
                "organisation": {
                    "type": "object",
                    "required": [
                        "name",
                        "href",
                        "title"
                    ],
                    "properties": {
                        "name": {
                            "type": "string",
                            "const": "Mapping and Geographic Information Centre, British Antarctic Survey"
                        },
                        "href": {
                            "type": "string",
                            "const": "https://ror.org/01rhff309"
                        },
                        "title": {
                            "type": "string",
                            "const": "ror"
                        }
                    }
                },
                "phone": {
                    "type": "string",
                    "const": "+44 (0)1223 221400"
                },
                "address": {
                    "type": "object",
                    "required": [
                        "delivery_point",
                        "city",
                        "administrative_area",
                        "postal_code",
                        "country"
                    ],
                    "properties": {
                        "delivery_point": {
                            "type": "string",
                            "const": "British Antarctic Survey, High Cross, Madingley Road"
                        },
                        "city": {
                            "type": "string",
                            "const": "Cambridge"
                        },
                        "administrative_area": {
                            "type": "string",
                            "const": "Cambridgeshire"
                        },
                        "postal_code": {
                            "type": "string",
                            "const": "CB3 0ET"
                        },
                        "country": {
                            "type": "string",
                            "const": "United Kingdom"
                        }
                    }
                },
                "email": {
                    "type": "string",
                    "const": "magic@bas.ac.uk"
                },
                "online_resource": {
                    "type": "object",
                    "required": [
                        "href",
                        "title",
                        "description",
                        "function"
                    ],
                    "properties": {
                        "href": {
                            "type": "string",
                            "const": "https://www.bas.ac.uk/teams/magic"
                        },
                        "title": {
                            "type": "string",
                            "const": "Mapping and Geographic Information Centre (MAGIC) - BAS public website"
                        },
                        "description": {
                            "type": "string",
                            "const": "General information about the BAS Mapping and Geographic Information Centre (MAGIC) from the British Antarctic Survey (BAS) public website."
                        },
                        "function": {
                            "type": "string",
                            "const": "information"
                        }
                    }
                }
            }
        },
        "maintenance": {
            "title": "Req. 12 - Update Frequency Code",
            "type": "object",
            "required": [
                "maintenance_frequency",
                "progress"
            ],
            "properties": {
                "progress": {
                    "$ref": "#/$defs/progress"
                }
            }
        },
        "metadata": {
            "type": "object",
            "required": [
                "contacts",
                "date_stamp",
                "constraints"
            ],
            "properties": {
                "contacts": {
                    "type": "array",
                    "contains": {
                        "$ref": "#/$defs/point_of_contact"
                    }
                },
                "constraints": {
                    "$ref": "#/$defs/constraints"
                }
            }
        },
        "point_of_contact": {
            "title": "Req. 08 - Point of contact",
            "allOf": [
                {
                    "$ref": "#/$defs/magic"
                },
                {
                    "type": "object",
                    "required": [
                        "role"
                    ],
                    "properties": {
                        "role": {
                            "type": "array",
                            "contains": {
                                "type": "string",
                                "const": "pointOfContact"
                            }
                        }
                    }
                }
            ]
        },
        "progress": {
            "title": "Req. 11 - Progress Code (Status)",
            "type": "string",
            "enum": [
                "completed",
                "deprecated",
                "onGoing",
                "retired",
                "superseded",
                "underDevelopment"
            ]
        }
    },
    "type": "object",
    "required": [
        "file_identifier",
        "hierarchy_level",
        "metadata",
        "identification"
    ],
    "properties": {
        "file_identifier": {
            "title": "Req. 01 - File Identifier",
            "type": "string"
        },
        "hierarchy_level": {
            "$ref": "#/$defs/hierarchy_level"
        },
        "metadata": {
            "$ref": "#/$defs/metadata"
        },
        "identification": {
            "$ref": "#/$defs/identification"
        }
    },
    "allOf": [
        {
            "if": {
                "description": "Conditional logic for container vs resource record super-types",
                "properties": {
                    "hierarchy_level": {
                        "$ref": "#/$defs/_resource_types"
                    }
                }
            },
            "then": {
                "properties": {
                    "identification": {
                        "title": "Req. 05 - Edition & Req. 13 - Lineage statement & Req. 15 - Citation",
                        "required": [
                            "edition",
                            "other_citation_details",
                            "identifiers",
                            "contacts",
                            "maintenance",
                            "constraints",
                            "extents",
                            "lineage",
                            "domain_consistency"
                        ]
                    }
                }
            }
        },
        {
            "if": {
                "description": "Conditional logic for released date if published",
                "properties": {
                    "identification": {
                        "required": [
                            "dates"
                        ],
                        "properties": {
                            "dates": {
                                "title": "Req. 07 - Publication Date",
                                "required": [
                                    "publication"
                                ]
                            }
                        }
                    }
                }
            },
            "then": {
                "properties": {
                    "identification": {
                        "properties": {
                            "dates": {
                                "title": "Req. 06 - Released Date",
                                "required": [
                                    "released"
                                ]
                            }
                        }
                    }
                }
            }
        }
    ]
}

=== antarctica/metadata-library/tests/resources/configs/magic-discovery-profile/minimal_resource_v2.json
{
  "$schema": "https://metadata-resources.data.bas.ac.uk/bas-metadata-generator-configuration-schemas/v2/iso-19115-2-v4.json",
  "file_identifier": "f9557951-30c7-4ab1-bb25-79a552d2c53d",
  "metadata": {
    "contacts": [
      {
        "organisation": {
          "name": "Mapping and Geographic Information Centre, British Antarctic Survey",
          "href": "https://ror.org/01rhff309",
          "title": "ror"
        },
        "phone": "+44 (0)1223 221400",
        "address": {
          "delivery_point": "British Antarctic Survey, High Cross, Madingley Road",
          "city": "Cambridge",
          "administrative_area": "Cambridgeshire",
          "postal_code": "CB3 0ET",
          "country": "United Kingdom"
        },
        "email": "magic@bas.ac.uk",
        "online_resource": {
          "href": "https://www.bas.ac.uk/teams/magic",
          "title": "Mapping and Geographic Information Centre (MAGIC) - BAS public website",
          "description": "General information about the BAS Mapping and Geographic Information Centre (MAGIC) from the British Antarctic Survey (BAS) public website.",
          "function": "information"
        },
        "role": [
          "pointOfContact"
        ]
      }
    ],
    "date_stamp": "2024-10-03",
    "constraints": [
      {
        "type": "access",
        "restriction_code": "unrestricted"
      },
      {
        "type": "usage",
        "restriction_code": "license",
        "statement": "This information is licensed under the Create Commons Attribution-NoDerivatives 4.0 International Licence (CC BY-ND 4.0). To view this licence, visit https://creativecommons.org/licenses/by-nd/4.0/",
        "href": "https://creativecommons.org/licenses/by-nd/4.0/"
      }
    ]
  },
  "hierarchy_level": "product",
  "identification": {
    "title": {
      "value": "Test resource record super-type with minimal MAGIC Discovery Profile properties"
    },
    "dates": {
      "creation": "2024-09-14"
    },
    "edition": "1",
    "identifiers": [
      {
        "identifier": "f9557951-30c7-4ab1-bb25-79a552d2c53d",
        "href": "https://data.bas.ac.uk/items/f9557951-30c7-4ab1-bb25-79a552d2c53d",
        "namespace": "data.bas.ac.uk"
      }
    ],
    "abstract": "An example product to verify resource super-type records with the minimal set of properties required by the MAGIC Discovery Profile is handled correctly.\n\nThis record does not include a publication date to test the 'false' branch of the released date conditional schema.",
    "contacts": [
      {
        "organisation": {
          "name": "Mapping and Geographic Information Centre, British Antarctic Survey",
          "href": "https://ror.org/01rhff309",
          "title": "ror"
        },
        "phone": "+44 (0)1223 221400",
        "address": {
          "delivery_point": "British Antarctic Survey, High Cross, Madingley Road",
          "city": "Cambridge",
          "administrative_area": "Cambridgeshire",
          "postal_code": "CB3 0ET",
          "country": "United Kingdom"
        },
        "email": "magic@bas.ac.uk",
        "online_resource": {
          "href": "https://www.bas.ac.uk/teams/magic",
          "title": "Mapping and Geographic Information Centre (MAGIC) - BAS public website",
          "description": "General information about the BAS Mapping and Geographic Information Centre (MAGIC) from the British Antarctic Survey (BAS) public website.",
          "function": "information"
        },
        "role": [
          "pointOfContact"
        ]
      },
      {
        "organisation": {
          "name": "UK Research and Innovation",
          "href": "https://ror.org/001aqnf71",
          "title": "ror"
        },
        "role": [
          "rightsHolder"
        ]
      }
    ],
    "maintenance": {
      "maintenance_frequency": "asNeeded",
      "progress": "completed"
    },
    "constraints": [
      {
        "type": "access",
        "restriction_code": "unrestricted"
      },
      {
        "type": "usage",
        "restriction_code": "license",
        "statement": "This information is licensed under the Open Government Licence (OGL 3.0). To view this licence, visit https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/.",
        "href": "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
      }
    ],
    "language": "eng",
    "extents": [
      {
        "identifier": "bounding",
        "geographic": {
          "bounding_box": {
            "west_longitude": -180.0,
            "east_longitude": 180.0,
            "south_latitude": -90.0,
            "north_latitude": -60.0
          }
        }
      }
    ],
    "other_citation_details": "Fictitious citation",
    "lineage": {
      "statement": "This is a fictitious record and has no real origin."
    },
    "domain_consistency": [
      {
        "specification": {
          "title": {
            "value": "British Antarctic Survey (BAS) Mapping and Geographic Information Centre (MAGIC) Discovery Metadata Profile",
            "href": "https://metadata-standards.data.bas.ac.uk/profiles/magic-discovery/v2/"
          },
          "dates": {
            "publication": "2025-11-24"
          },
          "edition": "2",
          "contact": {
            "organisation": {
              "name": "Mapping and Geographic Information Centre, British Antarctic Survey",
              "href": "https://ror.org/01rhff309",
              "title": "ror"
            },
            "phone": "+44 (0)1223 221400",
            "address": {
              "delivery_point": "British Antarctic Survey, High Cross, Madingley Road",
              "city": "Cambridge",
              "administrative_area": "Cambridgeshire",
              "postal_code": "CB3 0ET",
              "country": "United Kingdom"
            },
            "email": "magic@bas.ac.uk",
            "online_resource": {
              "href": "https://www.bas.ac.uk/teams/magic",
              "title": "Mapping and Geographic Information Centre (MAGIC) - BAS public website",
              "description": "General information about the BAS Mapping and Geographic Information Centre (MAGIC) from the British Antarctic Survey (BAS) public website.",
              "function": "information"
            },
            "role": [
              "publisher"
            ]
          }
        },
        "explanation": "Resource within scope of the British Antarctic Survey (BAS) Mapping and Geographic Information Centre (MAGIC) Discovery Metadata Profile.",
        "result": true
      }
    ]
  }
}
