=== antarctica/metadata-library/src/bas_metadata_library/schemas/src/iec_pas_61174_0_v1.json
{
  "$id": "https://metadata-standards.data.bas.ac.uk/bas-metadata-generator-configuration-schemas/v2/iec-pas-61174-0-v1.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "BAS Metadata Record Generator - IEC 61174:2015 v1 configuration schema",
  "description": "Metadata record configuration schema for the IEC 61174:2015 metadata standard (version 1)",
  "definitions": {
    "leg": {
      "type": "object",
      "required": [],
      "additionalProperties": false,
      "properties": {
        "geometry_type": {
          "title": "Geometry Type",
          "description": "Geometry type of leg (loxodrome [rhumb line] or orthodrome [great circle])",
          "type": "string",
          "enum": [
            "Loxodrome",
            "Orthodrome"
          ]
        }
      }
    },
    "position": {
      "type": "object",
      "required": [
        "lat",
        "lon"
      ],
      "additionalProperties": false,
      "properties": {
        "lat": {
          "title": "Latitude",
          "description": "Degrees latitude (decimal)",
          "type": "number",
          "minimum": -90.0,
          "maximum": 90.0,
          "examples": [
            50.75216574674486
          ]
        },
        "lon": {
          "title": "Longitude",
          "description": "Degrees longitude (decimal)",
          "type": "number",
          "minimum": -180.0,
          "maximum": 180.00,
          "examples": [
            -1.371093202427128
          ]
        },
        "geometry_type": {
          "title": "Geometry Type",
          "description": "Geometry type of leg (loxodrome [rhumb line] or orthodrome [great circle])",
          "type": "string",
          "enum": [
            "loxodrome",
            "orthodrome"
          ]
        }
      }
    },
    "route_author": {
      "title": "Route Author",
      "description": "Author of route",
      "type": "string",
      "examples": [
        "Constance Watson",
        "RoutePlanner 5000"
      ]
    },
    "route_name": {
      "title": "Route Name",
      "description": "Name of route",
      "type": "string",
      "pattern": "^[a-zA-Z0-9-_]+$",
      "examples": [
        "Route 51A"
      ]
    },
    "route_status": {
      "title": "Route Status",
      "description": "Description of route",
      "type": "string",
      "examples": [
        "Logistics run from base X to base y with opportunistic science transect"
      ]
    },
    "_schema": {
      "title": "JSON Schema",
      "description": "JSON Schema keyword indicating the schema a document complies with.",
      "type": "string",
      "format": "uri",
      "examples": [
        "https://metadata-standards.data.bas.ac.uk/bas-metadata-generator-configuration-schemas/v2/iec-pas-61174-0-v1.json"
      ]
  },
    "waypoints": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "revision",
          "position"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Identifier",
            "description": "Waypoint identifier, unique within route, value does NOT imply waypoint order",
            "type": "integer"
          },
          "revision": {
            "title": "Revision",
            "description": "Waypoint revision, indicating how many times a waypoint has been modified, 0 indexed",
            "type": "integer"
          },
          "position": {
            "$ref": "#/definitions/position"
          },
          "leg": {
            "$ref": "#/definitions/leg"
          }
        }
      }
    }
  },
  "type": "object",
  "required": [
    "route_name",
    "waypoints"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "$ref": "#/definitions/_schema"
    },
    "route_author": {
      "$ref": "#/definitions/route_author"
    },
    "route_name": {
      "$ref": "#/definitions/route_name"
    },
    "route_status": {
      "$ref": "#/definitions/route_status"
    },
    "waypoints": {
      "$ref": "#/definitions/waypoints"
    }
  }
}

=== antarctica/metadata-library/tests/resources/configs/iec-pas-61174-1/complete_v1.json
{
  "$schema": "https://metadata-resources.data.bas.ac.uk/bas-metadata-generator-configuration-schemas/v2/iec-pas-61174-1-v1.json",
  "route_author": "Constance Watson",
  "route_name": "complete-test-route",
  "route_status": "complete",
  "waypoints": [
    {
      "id": 1001,
      "revision": 0,
      "position": {
        "lat": 5.5,
        "lon": 50.55
      },
      "leg": {
        "geometry_type": "Orthodrome"
      }
    },
    {
      "id": 1002,
      "revision": 0,
      "position": {
        "lat": 5.5,
        "lon": 50.55
      },
      "leg": {
        "geometry_type": "Orthodrome"
      }
    },
    {
      "id": 1003,
      "revision": 0,
      "position": {
        "lat": 5.5,
        "lon": 50.55
      },
      "leg": {
        "geometry_type": "Orthodrome"
      }
    }
  ]
}
